### ISSUE TITLE
user_idはクエリパラメータやFormDataで受け取る時だけ指定する

### ISSUE THREAD

**Issue by norotime** [gosaru6/dive9#5]
https://github.com/gosaru6/dive9/blob/173688dbd975a15a78bd297ea718fe71e80dfcd0/app/controllers/blogs_controller.rb#L69

**Comment by norotime** [comment]
クエリパラメータとは
`「?」+「変数名」+「=」+「変数の値」というのが、クエリパラメータの基本構造`
https://webtan.impress.co.jp/e/2012/04/26/12663

**Comment by norotime** [comment]
https://developer.mozilla.org/ja/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

**Comment by norotime** [comment]
@gosaru6 user_idは、ログイン機能を実装していると、

*ブラウザのクッキー→HTTP→サーバのメモリ（session）で取得→プログラムで使う*

になりませんか？

**Comment by norotime** [comment]
そうすると user_id をストロングパラメータに入れるというのは、適切なのかどうかを考える必要があります。

**Comment by gosaru6** [comment]
すいません、複数ファイルのコミットになってしまいました…
確認お願いします！
